### ISSUE TITLE
[Feature Request]: 是否可以提供一个更加详细的教程

### ISSUE THREAD

**Issue by YeTianXingShi** [Aloereed/stable-diffusion-webui-arc-directml#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

我尝试了下载本仓库 然后运行 webui-user.bat 。安装完成一些依赖后出现了以下报错
![image](https://user-images.githubusercontent.com/42585691/227721910-e615bff3-0b71-42ea-95f3-09ea7b2f06f2.png)

我看readme中有一部分说的是  请确保以下仓库被下载。(包括 BLIP, CodeFromer, k-diffusion, stable-diffusion-stability-ai,taming-transformes) 
请问这个步骤是否可以描述的更加详细

### Proposed workflow

nothing

**Comment by Aloereed** [comment]
是网不行没有clone成功吗？

**Comment by YeTianXingShi** [comment]
> 是网不行没有clone成功吗？

不是 就是对于clone这个步骤 能出一个详细教程吗？  其中的内容包含 clone哪些仓库 clone下来的文件放在哪个目录。

**Comment by Aloereed** [comment]
这个没什么详细教程的。正常情况下直接执行程序就应该程序自己就会下好的。

**Comment by YeTianXingShi** [comment]
> 这个没什么详细教程的。正常情况下直接执行程序就应该程序自己就会下好的。

也就是说 正常情况下 只需要clone本仓库 并运行其中的webui-user.bat，就足够了。 我可以这样理解吗？

**Comment by Aloereed** [comment]
正常情况下是的。除了k-diffusion, stable-diffusion-stability-ai这两个仓库要下好放在repositories下之外，程序都会自己处理的。

**Comment by YeTianXingShi** [comment]
除了k-diffusion, stable-diffusion-stability-ai这两个仓库要下好放在repositories下  
关键的应该就是这个步骤 建议将这个步骤补充到reademe

**Comment by Aloereed** [comment]
readme里只有这2个仓库我加了超链接的。

**Comment by YeTianXingShi** [comment]
好的 感谢你~

**Comment by greatlei** [comment]
请问除了k-diffusion, stable-diffusion-stability-ai这两个仓库外的其他仓库，运行webui-user.bat都会自动下载好吗

**Comment by YeTianXingShi** [comment]
> 请问除了k-diffusion, stable-diffusion-stability-ai这两个仓库外的其他仓库，运行webui-user.bat都会自动下载好吗

yes

**Comment by greatlei** [comment]
> > 请问除了k-diffusion, stable-diffusion-stability-ai这两个仓库外的其他仓库，运行webui-user.bat都会自动下载好吗
> 
> yes

好的，谢谢~
